# Generated by Django 4.2.1 on 2023-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_typework'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_view',
            field=models.IntegerField(default=1),
        ),
    ]
