# Generated by Django 4.2.1 on 2023-05-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_category_category_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_view',
        ),
    ]
