# Generated by Django 4.2.1 on 2023-05-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_category_category_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typework',
            name='cost',
            field=models.IntegerField(default=1000),
        ),
    ]
